# Generated by Django 6.0.4 on 2026-05-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sinopse',
            field=models.TextField(blank=True),
        ),
    ]
