# Generated by Django 6.0.4 on 2026-05-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_sinopse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sinopse',
        ),
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.TextField(blank=True, null=True, verbose_name='Sinopse'),
        ),
    ]
